export default {
  login: "tranquangkhai2612",
  id: 103094267,
  node_id: "U_kgDOBiUX-w",
  avatar_url: "https://avatars.githubusercontent.com/u/103094267?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/tranquangkhai2612",
  html_url: "https://github.com/tranquangkhai2612",
  followers_url: "https://api.github.com/users/tranquangkhai2612/followers",
  following_url:
    "https://api.github.com/users/tranquangkhai2612/following{/other_user}",
  gists_url: "https://api.github.com/users/tranquangkhai2612/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/tranquangkhai2612/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/tranquangkhai2612/subscriptions",
  organizations_url: "https://api.github.com/users/tranquangkhai2612/orgs",
  repos_url: "https://api.github.com/users/tranquangkhai2612/repos",
  events_url: "https://api.github.com/users/tranquangkhai2612/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/tranquangkhai2612/received_events",
  type: "User",
  site_admin: false,
  name: "Trần Quang Khải",
  company: "none",
  blog: "https://www.facebook.com/tranquangkhai2612/",
  location: "HCMC, Vietnam",
  email: null,
  hireable: null,
  bio: "You only live once, but if you do it right, once is enough - Mae West -",
  twitter_username: "tranquangkhai2612",
  public_repos: 5,
  public_gists: 1,
  followers: 10,
  following: 20,
  created_at: "2022-04-06T04:59:31Z",
  updated_at: "2023-02-04T12:27:06Z",
};
